import { fileURLToPath, URL } from 'node:url';

import vue from '@vitejs/plugin-vue';

import { defineConfig } from 'vitest/config';

const local = (p) => fileURLToPath(new URL(p, import.meta.url)).replace(/\\/g, '/');

export default defineConfig({
	plugins: [ vue() ],
	resolve: {
		alias: [
			// this package imports its own files by package name
			{ find: /^@thzero\/library_client_vue3_vuetify3\//, replacement: local('./') },
			// supplied by the application's build
			{ find: 'local-config', replacement: local('./test/stubs/config.json') },
			// generated by the application's build
			{ find: 'open-source-config', replacement: local('./test/stubs/openSource.js') }
		],
		// as the applications' vite.config.js: imports name .vue files without the extension
		extensions: [ '.mjs', '.js', '.json', '.vue' ]
	},
	test: {
		environment: 'jsdom',
		// the first import transforms the whole dependency tree, cold
		testTimeout: 30000,
		include: [ 'test/**/*.test.js' ],
		setupFiles: [ 'test/setup.js' ],
		server: {
			deps: {
				// @thzero packages import without file extensions, which Vite resolves
				// but Node does not, so they must be transformed rather than externalized;
				// vuetify ships CSS imports Node cannot load
				inline: [ /@thzero\//, /vuetify/ ]
			}
		}
	}
});
